import Header from "./header";
import Footer from "./footer";
import { Metadata } from "next";

export const metadata : Metadata = {
  title: {
    absolute:'Home absolute',
    default:'Nextjs default',
    template:'%s | Narendra',
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
